// Historical corrections and references are separate from the diagram controls.
// A source supports the stated relationship, not a claim of a single founding year.
globalThis.applyTimelineHistory = function (nodes, edges) {
  const sources = {
    mesopotamia: ['Met Museum — Mesopotamian religion', 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/art-of-the-ancient-near-east.pdf'],
    pyramid: ['UCL — Pyramid Texts', 'https://www.ucl.ac.uk/museums-static/digitalegypt/literature/religious/pyramid.html'],
    egypt: ['Met Museum — Ancient Egypt', 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Art_of_Ancient_Egypt_A_Resource_for_Educators.pdf'],
    ugarit: ['Oxford — Ugaritic literary texts', 'https://academic.oup.com/british-academy-scholarship-online/book/14187/chapter-abstract/168042623'],
    israel: ['Yale — Origins of Israelite religion', 'https://oyc.yale.edu/religious-studies/rlst-145/lecture-2'],
    greek: ['Met Museum — Greek religion', 'https://www.metmuseum.org/essays/greek-gods-and-religious-practices'],
    roman: ['Met Museum — Roman religion', 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/roman.pdf'],
    avesta: ['Iranica — Avesta: composition and transmission', 'https://www.iranicaonline.org/articles/avesta-holy-book/'],
    zoroaster: ['Iranica — Disputed dates of Zoroaster', 'https://www.iranicaonline.org/articles/zoroaster-iii-zoroaster-in-the-avesta/'],
    mani: ['Iranica — Manichaeism', 'https://www.iranicaonline.org/articles/manicheism-parent/manicheism-1-general-survey/'],
    temples: ['Israel Antiquities Authority — Historical timeline', 'https://www.deadseascrolls.org.il/learn-about-the-scrolls/historical-timeline'],
    torah: ['Yale — Formation of the Pentateuch', 'https://oyc.yale.edu/religious-studies/rlst-145/lecture-4'],
    canon: ['My Jewish Learning — Formation of the Jewish canon', 'https://www.myjewishlearning.com/article/creating-the-jewish-canon/'],
    septuagint: ['Britannica — Septuagint', 'https://www.britannica.com/topic/Septuagint'],
    scrolls: ['Israel Museum — Dead Sea Scrolls', 'https://www.imj.org.il/en/wings/shrine-book/dead-sea-scrolls'],
    samaritans: ['Oxford — Samaritans', 'https://academic.oup.com/edited-volume/61673/chapter-abstract/548062125'],
    rabbinic: ['My Jewish Learning — Judaism after the Temple', 'https://www.myjewishlearning.com/article/judaism-after-the-temple/'],
    talmud: ['My Jewish Learning — Mishnah and the two Talmuds', 'https://www.myjewishlearning.com/article/talmud-101/'],
    karaite: ['Oxford — Karaite law and scriptural authority', 'https://academic.oup.com/book/3559/chapter-abstract/144827238'],
    kabbalah: ['My Jewish Learning — Kabbalah and Hasidism', 'https://www.myjewishlearning.com/article/kabbalah-and-hasidism/'],
    reform: ['My Jewish Learning — Reform Judaism', 'https://www.myjewishlearning.com/article/reform-judaism/'],
    orthodoxy: ['YIVO — Orthodox Judaism and Neo-Orthodoxy', 'https://encyclopedia.yivo.org/article/1484'],
    conservative: ['My Jewish Learning — Conservative Judaism', 'https://www.myjewishlearning.com/article/conservative-judaism-how-the-middle-became-a-movement/'],
    reconstruction: ['Reconstructing Judaism — Movement history', 'https://www.reconstructingjudaism.org/article/history-reconstructionist-zionism/'],
    christian: ['Harvard — Christian history', 'https://pluralism.org/christianity'],
    newtestament: ['Yale — New Testament history and literature', 'https://oyc.yale.edu/religious-studies/rlst-152'],
    gnostic: ['Cambridge — Nag Hammadi and the Gnosticism category', 'https://www.cambridge.org/core/books/nag-hammadi-codices-and-their-ancient-readers/christian-book-culture-new-philology-and-gnosticism/ADCD9900881B746F4E525692DC50C768'],
    athanasius: ['Harvard Theological Review — Athanasius and the canon', 'https://www.cambridge.org/core/journals/harvard-theological-review/article/abs/canon-formation-and-social-conflict-in-fourthcentury-egypt-athanasius-of-alexandrias-thirtyninth-festal-letter/32DE04D9904E7E77475FB529FA4B67BD'],
    councils: ['Oxford — Nicaea and later councils', 'https://academic.oup.com/book/11236'],
    eastern: ['World Council of Churches — Eastern Orthodox history', 'https://www.oikoumene.org/church-families/orthodox-churches-eastern'],
    oriental: ['World Council of Churches — Oriental Orthodox churches', 'https://www.oikoumene.org/church-families/orthodox-churches-oriental'],
    ethiopia: ['World Council of Churches — Ethiopian church history', 'https://www.oikoumene.org/member-churches/ethiopian-orthodox-tewahedo-church'],
    geez: ['Ethiopian Orthodox Church — Biblical canon', 'https://www.ethiopianorthodox.org/english/canonical/books.html'],
    geeztranslation: ['Oxford — Ethiopic translations from the Septuagint', 'https://academic.oup.com/edited-volume/34470/chapter-abstract/292469774'],
    eastchurch: ['Iranica — East Syriac and Sasanian church history', 'https://www.iranicaonline.org/articles/armeno-iranian-relations-in-the-pre-islamic-period/'],
    trent: ['Council of Trent — Fourth-session scripture decree', 'https://www.papalencyclicals.net/councils/trent/fourth-session.htm'],
    westminster: ['Westminster Confession — Canon and Apocrypha', 'https://www.rpcga.org/westminster-confession-of-1647/'],
    baptists: ['Oxford — Separatists and Baptists', 'https://academic.oup.com/book/36889/chapter-abstract/322118234'],
    quakers: ['Quakers in Britain — History', 'https://quaker.org.uk/faith/our-history/the-beginnings-of-quakerism'],
    methodism: ['United Methodist Church — Wesley and Methodism', 'https://www.umc.org/en/content/roots'],
    adventists: ['Adventist Church — Millerite roots and organization', 'https://adventist.org/identity/history'],
    lds: ['Latter-day Saint Church — History', 'https://newsroom.churchofjesuschrist.org/article/history-of-the-church-of-jesus-christ-of-latter-day-saints'],
    bom: ['Church History Library — Book of Mormon first edition', 'https://churchhistorylibrary.churchofjesuschrist.org/chl/foundations-of-faith-exhibit/2-3?lang=eng'],
    witnesses: ['Jehovah’s Witnesses — Adoption of the name in 1931', 'https://www.jw.org/en/news/region/global/Ninety-Years-Embracing-the-Name-Jehovahs-Witnesses/'],
    russell: ['Britannica — Charles Taze Russell', 'https://www.britannica.com/biography/Charles-Taze-Russell'],
    pentecostal: ['World Council of Churches — Pentecostal history', 'https://www.oikoumene.org/church-families/pentecostal-churches'],
    islam: ['Harvard — Islamic history', 'https://pluralism.org/islam'],
    lateantique: ['Cambridge — The Qur’an in its late-antique setting', 'https://www.cambridge.org/core/books/early-quran-in-mecca/introduction/CDEF78DDDBA7201ECAF580A8F0A27FA4'],
    kharijites: ['Iranica — Kharijite origins', 'https://www.iranicaonline.org/articles/kharijites-in-persia/'],
    ibadi: ['Oxford — Origins of Ibadi Islam', 'https://academic.oup.com/book/11314/chapter-abstract/159908889'],
    shia: ['Iranica — Shiʿite doctrine', 'https://www.iranicaonline.org/articles/shiite-doctrine/'],
    ismaili: ['Iranica — Ismaili history', 'https://www.iranicaonline.org/articles/ismailism-iii-ismaili-history/'],
    twelver: ['Iranica — Occultation', 'https://www.iranicaonline.org/articles/gayba/'],
    hadith: ['Britannica — Hadith', 'https://www.britannica.com/topic/Hadith'],
    sufi: ['Harvard — Sufism is not a separate sect', 'https://pluralism.org/sufism'],
    druze: ['Institute of Ismaili Studies — Druze origins', 'https://www.iis.ac.uk/glossary/druze/'],
    shaykhi: ['Iranica — Formation of Shaykhism', 'https://www.iranicaonline.org/articles/shaykhism/'],
    babi: ['Iranica — Bábí movement', 'https://www.iranicaonline.org/articles/babism-index/babism-i-the-babi-movement/'],
    bahai: ['Iranica — Bahá’í history', 'https://www.iranicaonline.org/articles/bahaism-index/bahaism-i/'],
    ahmadiyya: ['Ahmadiyya Muslim Community — History', 'https://www.alislam.org/ahmadiyya-muslim-community/'],
    hindu: ['Harvard — Hindu traditions and texts', 'https://pluralism.org/hinduism'],
    upanishads: ['Internet Encyclopedia of Philosophy — Upanishads', 'https://iep.utm.edu/upanisad/'],
    sramana: ['Cambridge — Buddhist and Jain ascetic traditions', 'https://assets.cambridge.org/97811070/33931/excerpt/9781107033931_excerpt.pdf'],
    theravada: ['Springer — Formation of Theravāda identity', 'https://link.springer.com/article/10.1007/s41682-022-00137-w'],
    pali: ['Pali Text Society — Canon and oral transmission', 'https://palitextsociety.org/wp-content/uploads/2024/07/PTS-List-of-Issues-from-July-2024.pdf'],
    buddhist: ['Harvard — Buddhist history and transmission', 'https://pluralism.org/buddhism'],
    tantra: ['British Museum — Tantra', 'https://www.britishmuseum.org/exhibitions/tantra-enlightenment-revolution'],
    advaita: ['Stanford — Śaṅkara and Advaita', 'https://plato.stanford.edu/entries/shankara/'],
    bhakti: ['Oxford — Tamil devotional traditions', 'https://academic.oup.com/reference/62357/reference-article-abstract/554509203'],
    nanak: ['Harvard — Guru Nanak', 'https://www.pluralism.org/files/pluralism/files/guru_nanak.pdf'],
    sikh: ['Harvard — Sikh history and scripture', 'https://pluralism.org/sikhism'],
    aryasamaj: ['Britannica — Arya Samaj', 'https://www.britannica.com/topic/Arya-Samaj'],
    confucius: ['Internet Encyclopedia of Philosophy — Confucius', 'https://iep.utm.edu/confucius/'],
    confucian: ['Harvard — Confucian history', 'https://pluralism.org/confucianism'],
    daoist: ['Stanford — Daoist thought and texts', 'https://plato.stanford.edu/entries/daoism/'],
    daoism: ['Harvard — Religious Daoism', 'https://pluralism.org/daoism'],
    korea: ['Met Museum — Buddhism in Korea and Japan', 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Arts_of_Korea_A_Resource_for_Educators.pdf'],
    shinto: ['Harvard — Shintō and Buddhist interaction', 'https://pluralism.org/shinto'],
    caodai: ['University of Hawai‘i Press — Cao Đài history and religious sources', 'https://academic.oup.com/hawaii-scholarship-online/book/15414'],
    rastafari: ['Oxford — African-Jamaican Christian roots of Rastafari', 'https://academic.oup.com/book/7570/chapter-abstract/152568126'],
    uu: ['Unitarian Universalist Association — History', 'https://www.uua.org/beliefs/who-we-are/history'],
    gilgamesh: ['Met Museum — Sumerian and Akkadian Gilgamesh texts', 'https://www.metmuseum.org/essays/gilgamesh'],
    zohar: ['Cambridge — Formation of the Zoharic canon', 'https://www.cambridge.org/core/books/abs/zohar-reception-and-impact/formation-of-the-zoharic-canon/7DDD1FF048FD256750CF3B546E1FEABA']
  };
  const byId = new Map(nodes.map(node => [node.id, node]));
  const revise = (id, changes) => Object.assign(byId.get(id), changes);
  revise('shaykhi', {
    year: 1826, shortDate: 'Early 19th century',
    date: 'Early 19th century; distinct school in the 1820s',
    dateBasis: 'The 1826 position marks the death of Shaykh Ahmad and the school’s clearer formation under his successor. His teaching began earlier.',
    desc: 'Twelver Shiʿi school based on Shaykh Ahmad al-Ahsa’i’s teachings. It became a distinct school in the early 19th century and was organized under Kazim Rashti. Some early Bábís came from this setting, but the two movements are not the same.',
    sources: ['shaykhi']
  });
  revise('orthjud', {
    name: 'Orthodox Judaism — modern identity', shortDate: '19th-century identity',
    date: 'Orthodox Judaism takes distinct modern forms in the 19th century; practices are older',
    dateBasis: 'The 1820 position is a display anchor for early 19th-century responses to reform, not a founding year.',
    desc: 'Orthodox Judaism developed a distinct modern identity while maintaining older rabbinic law and practice. It includes several approaches to modern life. Modern or Neo-Orthodoxy, associated with Hirsch and Hildesheimer, is one approach within this wider tradition.',
    sources: ['orthodoxy']
  });
  revise('avesta', {
    name: 'Avesta — Sasanian compilation', year: 350, shortDate: 'Sasanian compilation, c. 4th c. CE',
    date: 'Ancient oral texts; written compilation in the Sasanian era',
    dateBasis: 'The c. 350 CE position marks a proposed 4th-century written compilation. It does not date the composition of the Gāthās or other ancient Avestan texts.',
    desc: 'The Avesta preserves texts from several periods, including the older Gāthās and younger Avestan works. Oral transmission came first. The surviving written tradition derives from Sasanian compilation, with later losses and manuscript transmission.',
    sources: ['avesta']
  });
  revise('zoro', {sources: ['zoroaster'], dateBasis: 'The c. 1000 BCE position is a schematic marker. Scholarly dates differ by several centuries.'});
  revise('baptist', {
    date: 'General Baptists from 1609; Particular Baptists from the 1630s',
    desc: 'Baptist churches developed within English Puritan and Separatist settings. General Baptists emerged around Smyth and Helwys in 1609; Particular Baptists developed in the 1630s with Calvinist theology. These are related histories, not one Calvinist founding event.',
    sources: ['baptists']
  });
  nodes.push({id: 'englishdissent', name: 'English Puritan / Separatist currents', year: 1560,
    date: 'Later 16th century; several reform and separatist currents', shortDate: 'Later 16th century',
    group: 'Christian', type: 'movement', row: 2,
    desc: 'English Protestants sought further reform of the Church of England. Some formed separate congregations. These varied settings later gave rise to General and Particular Baptist churches.', sources: ['baptists']});
  edges.push({source: 'earlychrist', target: 'chalcedon', type: 'lineage'});
  edges.push({source: 'reformation', target: 'englishdissent', type: 'lineage'});
  edges.push({source: 'englishdissent', target: 'baptist', type: 'lineage'});

  // Membership and devotional practice do not mean institutional separation.
  const within = new Set(['islam|sufi', 'vaishnava|bhakti', 'shaiva|bhakti', 'rabbinic|kabbalah', 'oriental|ethiopian', 'brahmanical|advaita']);
  edges.forEach(edge => { if (within.has(`${edge.source}|${edge.target}`)) edge.type = 'within'; });

  // Short labels retain uncertainty and identify milestones. Never use the plot
  // coordinate as a replacement for historical date text.
  const shortDates = {
    oral: 'Prehistoric roots; ongoing', sumer: 'Written evidence c. 3200 BCE', egypt: 'c. 3100 BCE; older roots',
    pyramid: 'c. 2400–2300 BCE', akkad: '3rd–1st millennia BCE', gilgamesh: 'Old Babylonian text, c. 1800 BCE',
    bookdead: 'From c. 1550 BCE', canaan: 'Texts c. 1400–1200 BCE', baal: 'c. 14th–13th c. BCE',
    greek: 'c. 800 BCE; older roots', homer: 'c. 8th century BCE', roman: 'c. 500 BCE; older roots',
    indoiranian: '2nd millennium BCE; reconstructed', zoro: 'Date disputed; c. 1000 BCE marker', gathas: 'c. 1000 BCE; dating disputed',
    mani: '3rd century CE', yazidi: 'Medieval formation; 12th c. onward',
    israelite: 'Iron Age, c. 1200 BCE onward', firsttemple: 'Temple period, c. 10th–6th c. BCE',
    torah: 'Formation over centuries', secondtemple: 'c. 515 BCE–70 CE', tanakh: 'Canon formed over centuries',
    septuagint: 'Translations from c. 250 BCE', dss: '3rd c. BCE–1st c. CE', samaritan: 'Gradual distinction, 2nd–1st c. BCE',
    sampent: 'Distinct form, c. 2nd–1st c. BCE', rabbinic: 'Formation after 70 CE; older roots', mishnah: 'c. 200 CE',
    jtalmud: 'c. 4th–5th century CE', btalmud: 'Main redaction, c. 5th–6th c. CE', karaite: 'c. 8th–9th century CE',
    kabbalah: 'Medieval forms, 12th–13th c.', hasidic: '18th century', reformjud: 'Early 19th century',
    conservativejud: '19th century; JTS founded 1886', reconstruction: '1922 synagogue; movement later',
    earlychrist: '1st century CE', paul: 'c. 50s CE onward', gospels: 'c. 70–100 CE', gnostic: 'Especially 2nd–3rd centuries CE',
    nhworks: 'Works 2nd–3rd c.; codices 4th c.', nicaea: 'Council, 325 CE', aksum: '4th century CE', ntcanon: 'Athanasius’s list, 367 CE',
    chalcedon: 'Chalcedon accepted, 451 CE', oriental: 'Separation after 451 CE', ethiopian: '4th-c. roots; identity after 451',
    geezbible: 'Translations from late antiquity', eastchurch: 'Synod 410; autonomy 424 CE', eastorth: '1054: separation marker', catholic: '1054: separation marker',
    reformation: 'From 1517 CE', lutheran: '1520s', reformed: '1520s–1530s', anabaptist: 'From 1525', anglican: '16th century; 1534 legal break',
    trent: 'Canon decree, 1546 CE', protbible: '1647 confession; practice varied', baptist: '1609 / 1630s beginnings', quaker: 'Mid-17th century', methodist: '18th century',
    lds: 'Church organized 1830', bom: 'Published March 1830', miller: '1830s–1840s', sda: 'Organized 1863', biblestudents: '1870s', jw: 'Name adopted 1931; older roots',
    pentecostal: 'Early 20th c.; Azusa Street 1906', islam: 'Revelations c. 610; Medina 622', quran: 'Revelations c. 610–632', kharijite: 'From the First Fitna, 7th c.',
    shia: 'Earlier roots; Karbala 680', sunni: 'Identity develops, 7th–9th c.', ibadi: 'Late 7th–8th century', sufi: 'From 8th c.; orders later', ismaili: 'Succession dispute, 765 CE',
    twelver: 'Occultation from 874 CE', hadith: 'Major collections, 9th c.', druze: 'Early 11th century', babi: 'Founded 1844', bahai: 'Declaration 1863; Bábí roots', ahmadiyya: 'Founded 1889',
    indus: 'c. 2600–1900 BCE; uncertain', vedic: 'c. 1500–500 BCE', rigveda: 'Core c. 1500–1200 BCE; debated', brahmanical: '1st millennium BCE onward',
    upanishads: 'Old layers, c. 7th–4th c. BCE', sramana: 'c. 6th–5th centuries BCE', jain: 'Mahavira c. 6th–5th c. BCE', buddha: '5th c. BCE; chronology debated',
    ramayana: 'Late 1st millennium BCE–early CE', mahabharata: 'Composition c. 400 BCE–400 CE', gita: 'c. 2nd c. BCE–2nd c. CE', theravada: 'Sri Lankan roots, c. 3rd c. BCE',
    palicanon: 'Written c. 1st c. BCE; older orally', mahayana: 'c. 1st c. BCE–1st c. CE', vaishnava: 'Early CE formations; older roots', shaiva: 'Early CE formations; older roots',
    shakta: 'Mid-1st millennium CE; older roots', puranas: 'Major layers, c. 3rd–10th c. CE', tantra: 'Mid-1st millennium CE onward', vajra: 'c. 6th–8th c. CE onward',
    advaita: 'Śaṅkara, c. 8th c.; older roots', bhakti: 'Regional movements from c. 6th c.', sikh: 'Community forms c. 1500', adigranth: 'Compiled 1604', gurugranth: 'Authority as Guru, 1708',
    aryasamaj: 'Founded 1875', iskcon: 'Institution founded 1966', shang: 'Oracle bones c. 1250–1046 BCE', zhou: 'From c. 1046 BCE', confucius: 'Confucius, 551–479 BCE',
    analects: 'Compilation: Warring States–Han', daodejing: 'c. 4th–3rd century BCE', zhuangzi: 'Core c. 4th–3rd century BCE', daoistph: 'Warring States period',
    chinabuddh: 'Transmission by 1st–2nd c. CE', religdao: 'Celestial Masters, 2nd c. CE', pureland: 'East Asian forms from 4th–6th c.', chan: 'Traditional roots, c. 6th c. CE',
    japanbuddh: 'Official introduction: 538 or 552', shinto: 'Ancient roots; texts 712 / 720', neoconf: 'Especially 11th–12th centuries', zen: 'Schools from 12th–13th c.',
    tenrikyo: 'Founded 1838', caodai: 'Organized 1926', rastafari: 'Jamaica, 1930s', wicca: 'Public emergence in the 1950s', uu: 'Association merger, 1961',
    mandaean: 'Origins disputed; late antiquity', earlybuddhistschools: 'After the Buddha; dates debated', koreabuddh: 'Korean transmission from 372 CE', zohar: 'Main corpus, late 13th century'
  };
  nodes.forEach(node => { node.shortDate = shortDates[node.id] || node.shortDate; });

  // Each key identifies one connection. Notes state the kind of relationship;
  // they do not imply that this diagram includes every historical influence.
  const notes = {
    'sumer|akkad': ['Sumerian and Akkadian communities shared and adapted deities, myths and temple practices.', 'mesopotamia'],
    'egypt|pyramid': ['Royal funerary spells were inscribed in Egyptian pyramids.', 'pyramid'],
    'egypt|bookdead': ['Egyptian funerary traditions produced these changing collections of spells.', 'egypt'],
    'canaan|baal': ['The poems preserve Ugaritic accounts of Baal and other local deities.', 'ugarit'],
    'canaan|israelite': ['Israelite religion developed in the wider Canaanite world; this is regional context, not a single institutional split.', 'israel'],
    'greek|homer': ['The epics transmit Greek accounts of gods and heroes; they are not a fixed scriptural canon.', 'greek'],
    'greek|roman': ['Romans adopted and adapted Greek gods and myths alongside Italic and Etruscan traditions.', 'roman'],
    'indoiranian|zoro': ['Avestan language and ritual preserve a shared Indo-Iranian background.', 'zoroaster'],
    'zoro|gathas': ['These Old Avestan hymns are traditionally attributed to Zarathustra; their dates remain disputed.', 'zoroaster'],
    'gathas|avesta': ['Textual inclusion: the older Gāthās are preserved within the Avesta. Compilation is later than composition.', 'avesta'],
    'zoro|mani': ['Mani used Iranian religious terms and ideas within a distinct religious system.', 'mani'],
    'israelite|firsttemple': ['Judah’s Jerusalem temple tradition was one part of the wider Israelite religious world.', 'temples'],
    'firsttemple|secondtemple': ['Temple worship resumed after exile; Jewish life also changed during this transition.', 'temples'],
    'firsttemple|torah': ['Older Israelite and Judahite traditions form part of the Pentateuch’s textual background.', 'torah'],
    'secondtemple|tanakh': ['Jewish communities preserved and collected scriptures; the canon’s limits developed gradually.', 'canon'],
    'torah|tanakh': ['Textual inclusion: the Torah forms the first division of the Tanakh.', 'canon'],
    'tanakh|septuagint': ['Translation of Hebrew Jewish scriptures into Greek began before the Tanakh canon was fully fixed.', 'septuagint'],
    'secondtemple|septuagint': ['Greek-speaking Jewish communities produced and used these translations.', 'septuagint'],
    'secondtemple|dss': ['These manuscripts preserve scripture and other writings from Second Temple Jewish communities.', 'scrolls'],
    'israelite|samaritan': ['Samaritan and Judean traditions share Israelite roots; their separation was gradual.', 'samaritans'],
    'secondtemple|rabbinic': ['Rabbinic Judaism developed from Second Temple Jewish traditions, especially after the Temple’s destruction.', 'rabbinic'],
    'secondtemple|earlychrist': ['The Jesus movement began within the Jewish world of the Second Temple period.', 'christian'],
    'rabbinic|mishnah': ['Rabbinic legal teachings were collected and edited in the Mishnah.', 'talmud'],
    'mishnah|jtalmud': ['Commentary: Palestinian rabbinic discussions interpret and expand the Mishnah.', 'talmud'],
    'mishnah|btalmud': ['Commentary: Babylonian rabbinic discussions interpret and expand the Mishnah.', 'talmud'],
    'rabbinic|karaite': ['Karaites challenged the binding authority of rabbinic oral law; this is a relationship of debate, not agreement.', 'karaite'],
    'rabbinic|kabbalah': ['Kabbalah developed as Jewish mystical interpretation within rabbinic religious life, not a separate denomination.', 'kabbalah'],
    'kabbalah|hasidic': ['Hasidic teachers drew on earlier Kabbalistic ideas and practices.', 'kabbalah'],
    'rabbinic|hasidic': ['Hasidism arose as a devotional renewal within Eastern European rabbinic Judaism.', 'kabbalah'],
    'rabbinic|reformjud': ['Reform communities revised inherited Jewish worship and approaches to religious law.', 'reform'],
    'rabbinic|orthjud': ['Orthodox communities defended inherited rabbinic law while developing distinct responses to modern conditions.', 'orthodoxy'],
    'rabbinic|conservativejud': ['Conservative Judaism combined commitment to Jewish law with historical study and controlled change.', 'conservative'],
    'conservativejud|reconstruction': ['Kaplan developed Reconstructionism within the Conservative institutional setting; a separate movement formed gradually.', 'conservative', 'reconstruction'],
    'earlychrist|paul': ['Paul wrote letters to early Christian communities; these later entered the New Testament.', 'newtestament'],
    'earlychrist|gospels': ['Christian communities produced the four narratives later received as canonical Gospels.', 'newtestament'],
    'earlychrist|gnostic': ['Christian, Jewish and Platonic ideas overlap in these texts and movements; “Gnosticism” is a debated category.', 'gnostic'],
    'gnostic|nhworks': ['The collection preserves several related works, but not every Nag Hammadi text belongs to one Gnostic school.', 'gnostic'],
    'earlychrist|nicaea': ['Event: bishops met in an imperial council to address Christian doctrinal disputes.', 'councils'],
    'earlychrist|aksum': ['Christianity became established in Aksum through regional contacts and the work associated with Frumentius.', 'ethiopia'],
    'earlychrist|ntcanon': ['Canon witness: Athanasius listed these 27 books in 367; acceptance elsewhere was not immediate.', 'athanasius'],
    'septuagint|earlychrist': ['Early Christians used Greek Jewish scriptures in teaching and interpretation.', 'septuagint'],
    'nicaea|chalcedon': ['Event context: Chalcedon received and interpreted the earlier Nicene teaching.', 'councils'],
    'chalcedon|eastorth': ['Eastern churches continued the Chalcedonian tradition; separation from Rome developed over centuries.', 'eastern'],
    'chalcedon|catholic': ['Western churches continued the Chalcedonian tradition; 1054 is not the start of the Roman church.', 'eastern'],
    'aksum|ethiopian': ['Continuity of the Ethiopian church from Aksum; this does not mark a new foundation in 500.', 'ethiopia'],
    'oriental|ethiopian': ['The Ethiopian church belongs to the Oriental Orthodox family; this is shared communion, not a new founding.', 'ethiopia'],
    'aksum|geezbible': ['Ethiopian Christian communities developed and preserved a Geʿez biblical tradition over many centuries.', 'ethiopia', 'geez'],
    'septuagint|geezbible': ['Translation: Greek biblical texts were a major source for the early Geʿez Old Testament.', 'geeztranslation'],
    'catholic|reformation': ['Reform movements arose within Western Christianity and produced separate Protestant churches.', 'christian'],
    'reformation|lutheran': ['Lutheran churches developed from Luther’s reform movement and allied communities.', 'christian'],
    'reformation|reformed': ['Swiss and related reforms developed the Reformed tradition, including Zwingli and Calvin.', 'christian'],
    'reformation|anabaptist': ['Radical Reformation groups formed communities based on believers’ baptism.', 'christian'],
    'reformation|anglican': ['English reform and the break with papal authority shaped Anglican churches; Catholic continuity also remained.', 'christian'],
    'catholic|trent': ['Canon decree: Trent formally listed the Catholic scriptural books in 1546.', 'trent'],
    'reformation|protbible': ['Canon reception: Westminster lists 66 canonical books; Protestant printing practices still varied.', 'westminster'],
    'reformed|baptist': ['Calvinist theology shaped Particular Baptists; this does not describe the origins of all Baptist churches.', 'baptists'],
    'reformation|quaker': ['Friends emerged from the wider English Protestant religious setting, not from one direct Lutheran split.', 'quakers'],
    'anglican|methodist': ['The Wesleyan revival began within the Church of England before separate Methodist institutions formed.', 'methodism'],
    'reformation|lds': ['The movement arose in a Protestant restorationist setting but made distinct claims about restored authority.', 'lds'],
    'reformation|miller': ['Miller’s preaching developed within American Protestant revival culture.', 'adventists'],
    'miller|sda': ['Sabbatarian Adventists developed after Millerism; the denomination organized in 1863.', 'adventists'],
    'biblestudents|jw': ['One branch of the Bible Student movement adopted the name Jehovah’s Witnesses in 1931.', 'witnesses'],
    'methodist|pentecostal': ['Wesleyan Holiness and revival traditions contributed to Pentecostalism, alongside other streams.', 'pentecostal'],
    'lds|bom': ['Scriptural authority: the movement uses the Book of Mormon. Publication in March preceded church organization in April 1830.', 'bom', 'lds'],
    'rabbinic|islam': ['Jewish communities and traditions formed part of Islam’s late-antique setting; this is not denominational descent.', 'lateantique'],
    'islam|quran': ['Islam’s scripture preserves revelations proclaimed by Muhammad; collection and standardization followed.', 'islam'],
    'islam|kharijite': ['The first Kharijite currents arose from disputes over arbitration during the First Fitna.', 'kharijites'],
    'islam|shia': ['Shiʿi communities developed around the authority of Ali and his successors; identity formed gradually.', 'shia'],
    'islam|sunni': ['Sunni identity developed within early Muslim communities through teaching, law and transmission of the sunna.', 'islam', 'hadith'],
    'kharijite|ibadi': ['Ibadis share roots with early Muhakkima currents but reject identification with later extreme Kharijite groups.', 'ibadi'],
    'islam|sufi': ['Sufi practice exists within Sunni and Shiʿi Islam. It is not a third sect or one institutional split.', 'sufi'],
    'shia|ismaili': ['Succession disputes after Jaʿfar al-Sadiq’s death in 765 contributed to Ismaili lineages.', 'ismaili'],
    'shia|twelver': ['The line of twelve Imams and the occultation doctrine distinguish Twelver Shiʿism.', 'twelver'],
    'sunni|hadith': ['Collection and reception: these compilations became authoritative in Sunni traditions over time.', 'hadith'],
    'ismaili|druze': ['The Druze community arose from the Fatimid Ismaili setting and developed a distinct faith.', 'druze'],
    'twelver|shaykhi': ['Shaykhism formed as a distinct school of Twelver Shiʿi interpretation in the early 19th century.', 'shaykhi'],
    'shaykhi|babi': ['Some early Bábís came from Shaykhi circles. Their later religious claims broke with that setting.', 'shaykhi', 'babi'],
    'babi|bahai': ['Bahá’u’lláh and his early followers came from the Bábí movement; the Bahá’í Faith became independent.', 'bahai'],
    'islam|ahmadiyya': ['Ahmadiyya arose as an Islamic revival movement with distinctive claims about Mirza Ghulam Ahmad.', 'ahmadiyya'],
    'indoiranian|vedic': ['Vedic and Iranian language and ritual show a reconstructed common Indo-Iranian background.', 'zoroaster'],
    'vedic|rigveda': ['The hymns preserve an early Vedic poetic and ritual tradition transmitted orally.', 'hindu'],
    'vedic|brahmanical': ['Later Brahmanical traditions developed Vedic ritual, teaching and social practices.', 'hindu'],
    'vedic|upanishads': ['The early Upanishads form part of Vedic literature and reinterpret ritual and knowledge.', 'upanishads'],
    'vedic|sramana': ['Renunciant communities interacted and debated with Brahmanical traditions; this is not a descent claim.', 'sramana'],
    'sramana|jain': ['Jain communities developed within the wider North Indian renunciant setting.', 'sramana'],
    'sramana|buddha': ['The Buddha taught within the wider renunciant setting while developing a distinct path.', 'sramana'],
    'brahmanical|ramayana': ['The epic transmits and reworks religious narratives within Sanskrit and later Hindu traditions.', 'hindu'],
    'brahmanical|mahabharata': ['The epic collects many Hindu narratives and teachings; composition continued over centuries.', 'hindu'],
    'mahabharata|gita': ['Textual inclusion: the Bhagavad Gita is a section of the Mahabharata.', 'hindu'],
    'theravada|palicanon': ['Canonical authority: Theravāda communities preserve the Pāli collection, including older oral material.', 'pali'],
    'brahmanical|vaishnava': ['Vishnu-centered traditions developed within the wider Hindu world, drawing on several older sources.', 'hindu'],
    'brahmanical|shaiva': ['Shiva-centered traditions developed within the wider Hindu world, drawing on several older sources.', 'hindu'],
    'brahmanical|shakta': ['Goddess-centered traditions developed within the wider Hindu world; they do not have a single origin.', 'hindu'],
    'brahmanical|puranas': ['These evolving textual collections transmit myths, rituals and teachings across Hindu traditions.', 'hindu'],
    'shaiva|tantra': ['Scriptural production and use: Shaiva traditions preserve many Tantras and Āgamas.', 'tantra'],
    'shakta|tantra': ['Scriptural production and use: Shakta traditions preserve goddess-centered Tantras.', 'tantra'],
    'mahayana|vajra': ['Tantric Buddhist practices developed within Mahāyāna traditions rather than replacing them.', 'buddhist', 'tantra'],
    'upanishads|advaita': ['Scriptural interpretation: Advaita develops nondual readings of the Upanishads.', 'advaita'],
    'gita|advaita': ['Scriptural interpretation: Śaṅkara and later Advaitins commented on the Bhagavad Gita.', 'advaita'],
    'vaishnava|bhakti': ['Vishnu-centered devotion is one stream of Bhakti; Bhakti is not a separate successor denomination.', 'bhakti'],
    'shaiva|bhakti': ['Shiva-centered devotion is one stream of Bhakti; Bhakti is not a separate successor denomination.', 'bhakti'],
    'sufi|sikh': ['Sufi devotion formed part of Nanak’s regional setting; Sikhism developed an independent path.', 'nanak'],
    'bhakti|sikh': ['Indic devotional teaching formed part of Nanak’s regional setting; this is not institutional descent.', 'nanak'],
    'sikh|adigranth': ['Compilation: Guru Arjan assembled the Ādi Granth in 1604.', 'sikh'],
    'adigranth|gurugranth': ['Textual continuity and authority: the expanded scripture received final authority as Guru in 1708.', 'sikh'],
    'vedic|aryasamaj': ['Arya Samaj sought a modern return to Vedic authority, not an unchanged ancient institution.', 'aryasamaj'],
    'vaishnava|iskcon': ['ISKCON is a modern institution within the Gaudiya Vaishnava teaching lineage.', 'hindu'],
    'shang|zhou': ['Zhou rulers continued and changed earlier Chinese ritual traditions after replacing the Shang dynasty.', 'confucian'],
    'zhou|confucius': ['Confucius drew on Zhou ritual and political ideals.', 'confucius'],
    'confucius|analects': ['Collected teaching: sayings attributed to Confucius and his followers were assembled over time.', 'confucius'],
    'zhou|daoistph': ['Daoist texts arose within debates over inherited Chinese ritual and political order.', 'daoist'],
    'daoistph|daodejing': ['The text is a main basis for the later category of classical Daoist thought, not a church publication.', 'daoist'],
    'daoistph|zhuangzi': ['The text is a main basis for the later category of classical Daoist thought; it has several authors and layers.', 'daoist'],
    'mahayana|chinabuddh': ['Mahāyāna texts and teachings became important in China; other Buddhist traditions also arrived.', 'buddhist'],
    'chinabuddh|pureland': ['Chinese Buddhists developed Pure Land practices from Mahāyāna teachings about Amitabha.', 'buddhist'],
    'chinabuddh|chan': ['Chan developed within Chinese Buddhist communities and their meditation traditions.', 'buddhist'],
    'daoistph|religdao': ['Religious Daoist movements adopted and reinterpreted classical texts alongside other ritual sources.', 'daoism'],
    'confucius|neoconf': ['Song-era thinkers renewed Confucian study and teaching; this is intellectual continuity, not a church split.', 'confucian'],
    'chinabuddh|neoconf': ['Neo-Confucian thinkers responded to and used ideas from Buddhist thought.', 'confucian'],
    'religdao|neoconf': ['Neo-Confucian thinkers responded to and used ideas from Daoist thought.', 'confucian'],
    'chan|zen': ['Chinese Chan teaching lineages were transmitted to Japan and developed as Zen schools.', 'buddhist'],
    'japanbuddh|zen': ['Zen schools developed within Japan’s wider Buddhist religious setting.', 'buddhist'],
    'confucius|caodai': ['Cao Đài draws on Confucian ethical and religious traditions.', 'caodai'],
    'religdao|caodai': ['Cao Đài draws on Daoist religious traditions.', 'caodai'],
    'chinabuddh|caodai': ['East Asian Buddhist teachings are among the sources used by Cao Đài.', 'caodai'],
    'catholic|caodai': ['Christian ideas and forms contributed to Cao Đài; this is not descent from the Catholic Church.', 'caodai'],
    'ethiopian|rastafari': ['Ethiopian imperial and biblical symbolism shaped Rastafari, not institutional descent from this church.', 'rastafari'],
    'baptist|rastafari': ['Native Baptist and Revival traditions contributed to Rastafari’s African-Jamaican Christian setting.', 'rastafari'],
    'reformation|uu': ['Unitarian and Universalist Christian traditions are historical roots of the later pluralist association.', 'uu'],
    'earlychrist|eastchurch': ['East Syriac churches developed in the Sasanian world; their autonomy predates the Chalcedonian division.', 'eastchurch'],
    'earlychrist|mani': ['Mani grew up in a Jewish-Christian baptist setting and adapted Christian ideas.', 'mani'],
    'buddha|mani': ['Manichaeism engaged Buddhist ideas and terminology; this influence was more limited than its Christian background.', 'mani'],
    'japanbuddh|shinto': ['Buddhist and kami traditions interacted for centuries; neither is simply descended from the other.', 'shinto'],
    'miller|biblestudents': ['Post-Millerite Adventist teachers influenced Russell’s Bible-study movement.', 'russell'],
    'earlychrist|islam': ['Christian communities and traditions formed part of Islam’s late-antique setting; this is not denominational descent.', 'lateantique'],
    'secondtemple|torah': ['Redaction and transmission: the Pentateuch took shape across the Persian and early Second Temple periods.', 'torah'],
    'samaritan|sampent': ['Scriptural authority: Samaritan communities use their form of the Pentateuch.', 'samaritans'],
    'torah|sampent': ['Textual relationship: the Samaritan Pentateuch shares older Torah material and has distinctive readings.', 'samaritans'],
    'tanakh|karaite': ['Scriptural authority: Karaites treat the Hebrew Bible, rather than rabbinic oral law, as binding.', 'karaite'],
    'earlychrist|oriental': ['Ancient regional churches formed a separate communion after rejection of Chalcedon; they did not descend from Chalcedonian churches.', 'oriental'],
    'buddha|chinabuddh': ['Indian and Central Asian teachers and texts transmitted Buddhism to China.', 'buddhist'],
    'brahmanical|advaita': ['Advaita is a Vedānta school within the wider Brahmanical tradition, not a separate religion.', 'advaita'],
    'brahmanical|aryasamaj': ['Arya Samaj arose as a modern Hindu reform movement.', 'aryasamaj'],
    'kabbalah|zohar': ['Textual production and reception: the Zohar became central to Kabbalistic interpretation.', 'zohar'],
    'sumer|gilgamesh': ['Earlier Sumerian stories supplied material for the later Akkadian epic.', 'gilgamesh'],
    'akkad|gilgamesh': ['Textual production: Babylonian writers formed and revised the Akkadian epic.', 'gilgamesh'],
    'buddha|earlybuddhistschools': ['Buddhist communities developed several teaching and monastic lineages after the Buddha.', 'theravada'],
    'earlybuddhistschools|theravada': ['Sri Lankan Buddhist institutions developed through early school lineages; the later identity was gradual.', 'theravada'],
    'earlybuddhistschools|mahayana': ['Mahāyāna developed within several Buddhist communities, not through one founding schism.', 'buddhist'],
    'chinabuddh|koreabuddh': ['Transmission: Buddhist teachers, texts and images entered the Korean kingdoms from China.', 'korea'],
    'koreabuddh|japanbuddh': ['Transmission: Baekje played a central role in Japan’s official introduction, dated 538 or 552.', 'korea'],
    'earlychrist|chalcedon': ['Continuity: churches that accepted Chalcedon in 451 continued earlier Christian communities. The council did not create Christianity.', 'councils', 'eastern'],
    'reformation|englishdissent': ['English Protestant reform produced Puritan and Separatist currents with different views of church order.', 'baptists'],
    'englishdissent|baptist': ['General Baptists arose from Separatism; Particular Baptists developed in the English Puritan and independent church setting.', 'baptists']
  };
  edges.forEach(edge => {
    const key = `${edge.source}|${edge.target}`;
    const note = notes[key];
    if (!note) throw new Error(`Missing historical note: ${key}`);
    edge.label = note[0];
    edge.sources = note.slice(1);
  });
  return sources;
};
